---
title: "Data Visualisation"
author: "Group 18"
date: '2022-04-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Library
```{r}
library("tidyverse")
library("patchwork")
library("ggridges")
```

# Loading of data 
```{r}
clean_data <- read.csv("../data/02_my_data_clean.tsv", sep = "\t")
```

# Cohort
```{r}
ggplot(data = clean_data, 
       mapping = aes(y = age, 
                     x = patient_cohort, 
                     color= diagnosis)) + 
  geom_boxplot()
```


```{r}
ggplot(data = clean_data, 
       mapping = aes(x = patient_cohort, 
                     y = creatinine, 
                     color = diagnosis)) + 
  geom_boxplot()
```

```{r}
ggplot(data = clean_data, 
       mapping = aes(x = patient_cohort, 
                     y = LYVE1, 
                     color = diagnosis)) + 
  geom_boxplot()
```

```{r}
ggplot(data = clean_data, 
       mapping = aes(x = patient_cohort, 
                     y = REG1B, 
                     color = diagnosis)) + 
  geom_boxplot()
```

```{r}
ggplot(data = clean_data, 
       mapping = aes(x = patient_cohort, 
                     y = TFF1, 
                     color = diagnosis)) + 
  geom_boxplot()
```

```{r}
ggplot(data = clean_data, 
       mapping = aes(x = patient_cohort, 
                     y = plasma_CA19_9, 
                     color = diagnosis)) + 
  geom_boxplot()
```

# Age Distribution 
```{r}
age_distribution <- clean_data %>% 
  ggplot(aes(x = age, 
             fill = diagnosis)) +
  geom_bar() + 
  theme_minimal() + 
  labs(title = "Age Distribution Across Different Diagnosis Groups", 
       x = "Age", 
       y = "Count")
```

```{r}
  age_distribution

```






# Sex Distribution 
```{r}
clean_data %>% 
  count(sex) %>% 
  ggplot(aes(x = "", 
             y = n, 
             fill = sex)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  geom_text(aes(label = n),
            position = position_stack(vjust = 0.5)) + 
  
  theme_void() # remove background, grid, numeric labels
```


# Demographics and clinical characteristics of patients and control individuals.
```{r}

```

# Age & Sex distribution 
```{r}

age_distribution <- clean_data %>% 
  ggplot(aes(x = age, 
             color = diagnosis)) +
  geom_density() + 
  theme_minimal(base_size = 10) + 
  labs(title = "Age Distribution Across Different Diagnosis Groups", 
       x = "Age", 
       y = "Density", 
       color = "Diagnosis Group") + 
  scale_color_discrete(labels = c("Begnin", "Control", "Malignant"))


sex_distribution <- ggplot(data = clean_data, 
                           mapping = aes(x = diagnosis, 
                     fill = sex)) + 
  geom_bar(stat="count", 
           position = position_dodge()) + 
  geom_text(stat = "count", 
            aes(label= ..count..), 
            position = position_dodge(1), 
            vjust = -0.3, 
            size = 2) + 
  theme_minimal(base_size = 10) + 
  theme(legend.position = "right") + 
  labs(title = "Sex Distribution Across Different Diagnosis Groups", 
       x = "Diagnosis Group", 
       y = "Count", 
       fill = "Sex") + 
  scale_x_discrete(labels = c("Benign", "Control", "PDAC"))


clinical_plot <- (age_distribution / sex_distribution)
clinical_plot
```


# Pie chart 
```{r}
clean_data %>% 
  count(diagnosis) %>% 
  mutate(percentage = round(n/sum(n)*100), 3) %>% 
  ggplot(aes(x = "", 
             y = percentage, 
             fill = diagnosis)) +
  geom_bar(stat = "identity", 
           width = 1, 
           color = "white") +
  coord_polar("y", 
              start = 0) +
  geom_text(aes(label = paste0(percentage, "%")),
            position = position_stack(vjust = 0.5), 
            size = 4) + 
  
  theme_void(base_size = 8) +  # remove background, grid, numeric labels  
  labs(title = "Diagnosis Group Distribution", 
       fill = "Diagnosis Group") + 
  scale_fill_discrete(labels = c("Benign", "Control", "PDAC"))

```






# Stage Distribution 


```{r}

diagnosis_percentage <- clean_data %>%
  count(diagnosis) %>% 
  mutate(Diagnosis = "Diagnosis Group", 
         percentage = round(n/sum(n)*100), digits = 2) %>% 
  ggplot(mapping = aes(fill = diagnosis, 
                       x = n, 
                       y = Diagnosis)) + 
  geom_col() + 
  scale_fill_brewer(palette = "Pastel2", 
                    labels = c("Begnin", "Control", "Malignant")) + 
  geom_text(aes(label = paste0(percentage, "%")),
            position = position_stack(vjust = 0.5), 
            size = 4) +
  theme_minimal(base_size = 10) + 
  labs(x = NULL, 
       y = NULL, 
       title = "Diagnosis Group Distribution", 
       fill = "Diagnosis Group") + 
  theme(legend.key.height = unit(0.01, 'cm'), 
        legend.position = "right") 
  #scale_fill_discrete(labels = c("Begnin", "Control", "Malignant"))


# Stacked + percent
stage_precentage <- clean_data %>% 
  filter(!is.na(stage)) %>% 
  count(stage) %>% 
  mutate(Stage = "Stage", 
         proportion = round(n/sum(n)*100), digits = 2) %>% 
  ggplot(mapping = aes(fill = stage, 
                       x = n, 
                       y = Stage)) + 
  geom_col() + 
  scale_fill_brewer(palette = "Set2") + 
  geom_text(aes(label = paste0(proportion, "%")),
            position = position_stack(vjust = 0.5), 
            size = 3) +
  theme_minimal(base_size = 10) + 
  labs(x = "Number of Patients", 
       y = NULL, 
       title = "Malignant Patients Stages Distribution", 
       fill = "Stage") + 
  theme(legend.key.height = unit(0.01, 'cm'), 
        legend.position = "right")
  
diagnosis_stage_distribution <- (diagnosis_percentage / stage_precentage) + 
  plot_layout(heights = unit(c(3, 3), c('cm', 'cm')))

diagnosis_stage_distribution
```

```{r}
all_distribution <- (age_distribution / sex_distribution / diagnosis_percentage / stage_precentage) + 
  plot_layout(heights = unit(c(0.2, 0.1, 0.03, 0.03), c('npc', 'npc', 'npc', 'npc')))

all_distribution
```







# Sample distribution between cohorts regarding protein samples taken
```{r}
data_long <- clean_data %>% 
  select(patient_cohort, 
         plasma_CA19_9, 
         creatinine, 
         LYVE1, 
         REG1A, 
         REG1B, 
         TFF1) %>% 
  pivot_longer(!patient_cohort, 
               names_to = "protein", 
               values_to = "expression")

data_long %>%
  group_by(patient_cohort) %>%
  ggplot(mapping = aes(y = patient_cohort, 
                       fill = patient_cohort)) +
  facet_wrap(~protein, 
             ncol = 2, 
             scales = "free") +
  geom_bar() +
  xlab("Occurence of measured protein levels per Cohort ") +
  ylab("Cohort of patients") +
  labs(title = "Sample distribution between two cohorts of patients") +
  theme_minimal() +
  theme(legend.position="none")
```

#  Levels of the 3 biomarkers in control, benign, and  (PDAC) samples
```{r}
LYVEvscreatinine <- select(clean_data, diagnosis , stage , LYVE1, creatinine) %>%
      mutate(diagnosis = case_when(
      diagnosis == "control" ~ "control",
      diagnosis == "benign" ~ "benign",
      stage  == "IA" ~ "PDAC I-II",
      stage  == "IB" ~ "PDAC I-II",
      stage  == "IIA" ~ "PDAC I-II",
      stage  == "IIB" ~ "PDAC I-II",
      stage  == "III" ~ "PDAC III-IV",
      stage  == "IV" ~ "PDAC III-IV") , 
      LYVE1 = LYVE1 / creatinine  )

```


```{r}
LYVEvscreatinine_plot <-ggplot(data = LYVEvscreatinine, 
       mapping = aes(x = diagnosis, 
                     y = LYVE1, 
                     color = diagnosis)) + 
  geom_violin(trim=FALSE)+ 
  geom_boxplot(width=0.2)+
  labs(y = "LYVE1 ng/mg creatinine" , 
       title = "LYVE1") +
  theme_minimal(base_size = 10,
                base_family = "Avenir")+
  theme(legend.position = "none")

```



```{r}
REG1Bvscreatinine <- select(clean_data, diagnosis , stage , REG1B, creatinine) %>%
      mutate(diagnosis = case_when(
      diagnosis == "control" ~ "control",
      diagnosis == "benign" ~ "benign",
      stage  == "IA" ~ "PDAC I-II",
      stage  == "IB" ~ "PDAC I-II",
      stage  == "IIA" ~ "PDAC I-II",
      stage  == "IIB" ~ "PDAC I-II",
      stage  == "III" ~ "PDAC III-IV",
      stage  == "IV" ~ "PDAC III-IV"), 
      REG1B = REG1B/ creatinine)

```

```{r}
REG1Bvscreatinine_plot <- ggplot(data = REG1Bvscreatinine, 
       mapping = aes(x = diagnosis, 
                     y = REG1B, 
                     color = diagnosis)) + 
  geom_violin(trim=FALSE)+ 
  geom_boxplot(width=0.2)+
  labs(y = "REG1B ng/mg creatinine" , 
       title = "REG1B") +
  theme_minimal(base_size = 10,
                base_family = "Avenir")+
  theme(legend.position = "none")



```

```{r}
TFF1vscreatinine <- select(clean_data, diagnosis , stage , TFF1, creatinine) %>%
      mutate(diagnosis = case_when(
      diagnosis == "control" ~ "control",
      diagnosis == "benign" ~ "benign",
      stage  == "IA" ~ "PDAC I-II",
      stage  == "IB" ~ "PDAC I-II",
      stage  == "IIA" ~ "PDAC I-II",
      stage  == "IIB" ~ "PDAC I-II",
      stage  == "III" ~ "PDAC III-IV",
      stage  == "IV" ~ "PDAC III-IV"),
      TFF1 = TFF1/ creatinine)
    
```


```{r}
TFF1vscreatinine_plot <-ggplot(data = TFF1vscreatinine, 
       mapping = aes(x = diagnosis, 
                     y = TFF1, 
                     color = diagnosis)) + 
  geom_violin(trim=FALSE)+ 
  geom_boxplot(width=0.2)+
  labs(y = "TFF1 ng/mg creatinine" , 
       title = "TFF1") +
  theme_minimal(base_size = 10,
                base_family = "Avenir")+
  theme(legend.position = "none")

```


```{r}
violin_plot <- (LYVEvscreatinine_plot |REG1Bvscreatinine_plot |TFF1vscreatinine_plot )
violin + plot_annotation(
              title = "The levels of the 3 biomarkers in control, benign, and pancreatic ductal adenocarcinoma (PDAC) samples. " ,
              subtitle = "Violin plots are shown for each protein. All data were creatinine normalised ",
              caption= "Data from Silvana Debernardi et al" )& 
  theme(legend.position = 'none')
```





